"""name to plot

Revision ID: 0082d1e7bafe
Revises: 2e415b799ff0
Create Date: 2024-11-30 14:57:02.563573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0082d1e7bafe'
down_revision = '2e415b799ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
