"""Add settings update counter to Account model

Revision ID: 1bf0761ba535
Revises: 0622ba902227
Create Date: 2024-11-26 17:11:43.295938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf0761ba535'
down_revision = '0622ba902227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_gateway_pings', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('count_uploaded_files', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('count_page_loads', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('count_file_downloads', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('count_settings_updated', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('count_settings_updated')
        batch_op.drop_column('count_file_downloads')
        batch_op.drop_column('count_page_loads')
        batch_op.drop_column('count_uploaded_files')
        batch_op.drop_column('count_gateway_pings')

    # ### end Alembic commands ###
