"""source has head and devices

Revision ID: 2d2d47f2cac0
Revises: 6b27d972a809
Create Date: 2024-12-02 04:55:41.568970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2d47f2cac0'
down_revision = '6b27d972a809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('preview')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head', sa.String(length=500), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('devices', sa.String(length=500), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('devices')
        batch_op.drop_column('head')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
