"""overhaul to settings

Revision ID: 3eecdfc66e2d
Revises: 69fd721d58c0
Create Date: 2025-01-17 06:36:40.039827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eecdfc66e2d'
down_revision = '69fd721d58c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_manages_memory', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.drop_column('dt_rule')
        batch_op.drop_column('delete_scans_percent_remaining')
        batch_op.drop_column('delete_scans_days_old')
        batch_op.drop_column('alert_file_starts_with')
        batch_op.drop_column('delete_scans')
        batch_op.drop_column('node_payload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_payload', sa.VARCHAR(length=100), server_default=sa.text("('')"), nullable=False))
        batch_op.add_column(sa.Column('delete_scans', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('alert_file_starts_with', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('delete_scans_days_old', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('delete_scans_percent_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dt_rule', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('gateway_manages_memory')

    # ### end Alembic commands ###
