"""Initial migration.

Revision ID: 4349b8f7cb6b
Revises: 
Create Date: 2024-10-18 12:41:40.254244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4349b8f7cb6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(length=200), nullable=False),
    sa.Column('dt_rule', sa.String(length=50), nullable=False),
    sa.Column('max_file_size', sa.Integer(), nullable=False),
    sa.Column('use_cloud', sa.Boolean(), nullable=False),
    sa.Column('delete_scans', sa.Boolean(), nullable=False),
    sa.Column('delete_scans_days_old', sa.Integer(), nullable=True),
    sa.Column('delete_scans_percent_remaining', sa.Integer(), nullable=True),
    sa.Column('device_name_includes', sa.String(length=100), nullable=True),
    sa.Column('id_file_starts_with', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
