"""add node connection tracking fields

Revision ID: 5b93bf0f9885
Revises: 767afe70f561
Create Date: 2025-01-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5b93bf0f9885'
down_revision = '767afe70f561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('device_id', sa.String(length=50), nullable=True, server_default=''))
    op.add_column('node', sa.Column('battery_level', sa.Integer(), nullable=True))
    op.add_column('node', sa.Column('alert', sa.String(length=500), nullable=True, server_default=''))
    op.add_column('node', sa.Column('was_connected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'was_connected')
    op.drop_column('node', 'alert')
    op.drop_column('node', 'battery_level')
    op.drop_column('node', 'device_id')
    # ### end Alembic commands ### 