"""adding passwords

Revision ID: 69fd721d58c0
Revises: b7a30cb04517
Create Date: 2024-12-29 06:43:21.776485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fd721d58c0'
down_revision = 'b7a30cb04517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        # Add password_hash first - it can be nullable
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        
        # Add use_password with server default of False - no need for UPDATE
        batch_op.add_column(sa.Column('use_password', sa.Boolean(), 
                                    server_default=sa.text('0'),  # SQLite uses 0/1 for booleans
                                    nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        # Drop in reverse order
        batch_op.drop_column('use_password')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
