"""default and shown nav in Layout

Revision ID: 706d946ac635
Revises: 2d2d47f2cac0
Create Date: 2024-12-02 09:41:00.494604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706d946ac635'
down_revision = '2d2d47f2cac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('show_nav', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.drop_column('show_nav')
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
