"""Add performance indexes for dashboard queries

Revision ID: 767afe70f561
Revises: fdf6d0da2abc
Create Date: 2025-07-19 12:02:21.272583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767afe70f561'
down_revision = 'fdf6d0da2abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('file_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('gateway', schema=None) as batch_op:
        batch_op.drop_constraint('gateway_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.drop_constraint('layout_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_constraint('setting_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint('fk_source_file', type_='foreignkey')
        batch_op.drop_constraint('source_account_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_source_file', 'file', ['file_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'account', ['account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
    
    # Add performance indexes for dashboard queries
    op.create_index('idx_file_account_id', 'file', ['account_id'])
    op.create_index('idx_file_last_modified', 'file', ['last_modified'])
    op.create_index('idx_gateway_account_id', 'gateway', ['account_id'])
    op.create_index('idx_gateway_created_at', 'gateway', ['created_at'])
    op.create_index('idx_gateway_name', 'gateway', ['name'])
    op.create_index('idx_node_gateway_id', 'node', ['gateway_id'])
    op.create_index('idx_node_created_at', 'node', ['created_at'])
    op.create_index('idx_node_uuid', 'node', ['uuid'])


def downgrade():
    # Drop performance indexes
    op.drop_index('idx_file_account_id', table_name='file')
    op.drop_index('idx_file_last_modified', table_name='file')
    op.drop_index('idx_gateway_account_id', table_name='gateway')
    op.drop_index('idx_gateway_created_at', table_name='gateway')
    op.drop_index('idx_gateway_name', table_name='gateway')
    op.drop_index('idx_node_gateway_id', table_name='node')
    op.drop_index('idx_node_created_at', table_name='node')
    op.drop_index('idx_node_uuid', table_name='node')
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_source_file', type_='foreignkey')
        batch_op.create_foreign_key('source_account_id_fkey', 'account', ['account_id'], ['id'])
        batch_op.create_foreign_key('fk_source_file', 'file', ['file_id'], ['id'])

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('setting_account_id_fkey', 'account', ['account_id'], ['id'])

    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('layout_account_id_fkey', 'account', ['account_id'], ['id'])

    with op.batch_alter_table('gateway', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('gateway_account_id_fkey', 'account', ['account_id'], ['id'])

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('file_account_id_fkey', 'account', ['account_id'], ['id'])

    # ### end Alembic commands ###
