"""added Gateway model

Revision ID: 775aee24ae90
Revises: 2a37b371a5c2
Create Date: 2024-10-24 05:03:29.272811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775aee24ae90'
down_revision = '2a37b371a5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gateway')
    # ### end Alembic commands ###
