"""added source success and error

Revision ID: 780b996940f0
Revises: efdec8479fda
Create Date: 2024-11-29 09:01:00.117347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780b996940f0'
down_revision = 'efdec8479fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('error', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('error')
        batch_op.drop_column('success')

    # ### end Alembic commands ###
