"""max path level for source instead of groups

Revision ID: 99667ceb688c
Revises: bb34c9f09310
Create Date: 2025-01-26 05:54:15.807616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '99667ceb688c'
down_revision = 'bb34c9f09310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_path_level', sa.Integer(), server_default='0', nullable=False))
        batch_op.drop_column('groups')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False))
        batch_op.drop_column('max_path_level')

    # ### end Alembic commands ###
