"""clean account counts

Revision ID: 9b43d9661f17
Revises: 84ee4c921c3e
Create Date: 2025-02-08 05:17:53.533265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b43d9661f17'
down_revision = '84ee4c921c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('count_settings_updated')
        batch_op.drop_column('count_page_loads')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_page_loads', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('count_settings_updated', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
