"""new fields for plan tracking

Revision ID: a5eb1baf3410
Revises: 9b43d9661f17
Create Date: 2025-02-08 05:36:24.864178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eb1baf3410'
down_revision = '9b43d9661f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_uploads_mo', sa.Integer(), server_default='5000', nullable=False))
        batch_op.add_column(sa.Column('plan_storage_gb', sa.Integer(), server_default='100', nullable=False))
        batch_op.add_column(sa.Column('plan_versioned_backups', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('plan_start_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('storage_current_bytes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('storage_versioned_bytes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('count_uploaded_files_mo', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('count_uploaded_files_mo')
        batch_op.drop_column('storage_versioned_bytes')
        batch_op.drop_column('storage_current_bytes')
        batch_op.drop_column('plan_start_date')
        batch_op.drop_column('plan_versioned_backups')
        batch_op.drop_column('plan_storage_gb')
        batch_op.drop_column('plan_uploads_mo')

    # ### end Alembic commands ###
