"""advanced plot field

Revision ID: bb34c9f09310
Revises: c9d57bdd6e05
Create Date: 2025-01-24 15:21:25.882202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb34c9f09310'
down_revision = 'c9d57bdd6e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advanced', sa.String(length=500), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_column('advanced')

    # ### end Alembic commands ###
