"""remove head from source

Revision ID: bba60573ae5c
Revises: f7df3dbd559a
Create Date: 2024-12-11 04:34:28.154732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba60573ae5c'
down_revision = 'f7df3dbd559a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('head')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head', sa.VARCHAR(length=500), server_default=sa.text("('')"), nullable=False))

    # ### end Alembic commands ###
