"""rm include_archive

Revision ID: bdc840726136
Revises: a0e46fbf393c
Create Date: 2025-01-21 17:23:32.190464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc840726136'
down_revision = 'a0e46fbf393c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('include_archive')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_archive', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    # ### end Alembic commands ###
