"""file_filter is now directory_filter

Revision ID: ccc4a1932b86
Revises: d2b348e27910
Create Date: 2025-01-23 09:11:48.482645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc4a1932b86'
down_revision = 'd2b348e27910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directory_filter', sa.String(length=200), server_default='*', nullable=False))
        batch_op.add_column(sa.Column('include_subdirs', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_column('file_filter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_filter', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('include_subdirs')
        batch_op.drop_column('directory_filter')

    # ### end Alembic commands ###
