"""added node_paylaod to Setting

Revision ID: cf0ae58170bd
Revises: d65fc148461a
Create Date: 2024-11-10 10:08:41.234372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0ae58170bd'
down_revision = 'd65fc148461a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_payload', sa.String(length=100), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.drop_column('node_payload')

    # ### end Alembic commands ###
