"""rm devices from source

Revision ID: d2b348e27910
Revises: bdc840726136
Create Date: 2025-01-23 08:49:08.104248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b348e27910'
down_revision = 'bdc840726136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('devices')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devices', sa.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
