"""starts_with columns should not be null but empty

Revision ID: d65fc148461a
Revises: 4e213708d3e5
Create Date: 2024-10-24 07:44:03.975336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65fc148461a'
down_revision = '4e213708d3e5'
branch_labels = None
depends_on = None


def upgrade():
    # Ensure all existing NULL values in 'alert_file_starts_with' and 'id_file_starts_with' are updated to empty strings
    op.execute("UPDATE setting SET alert_file_starts_with = '' WHERE alert_file_starts_with IS NULL")
    op.execute("UPDATE setting SET id_file_starts_with = '' WHERE id_file_starts_with IS NULL")
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('id_file_starts_with',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('alert_file_starts_with',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('alert_file_starts_with',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id_file_starts_with',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
