"""rm plot.data

Revision ID: e1f79621f43a
Revises: 3eecdfc66e2d
Create Date: 2025-01-17 07:39:51.224908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f79621f43a'
down_revision = '3eecdfc66e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
