"""added groups array to Source

Revision ID: edab4d3400e1
Revises: ccc4a1932b86
Create Date: 2025-01-23 10:36:22.209394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edab4d3400e1'
down_revision = 'ccc4a1932b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('groups')

    # ### end Alembic commands ###
