"""added include_archive to source

Revision ID: f7df3dbd559a
Revises: 75f13ca35deb
Create Date: 2024-12-10 17:37:06.997503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7df3dbd559a'
down_revision = '75f13ca35deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('include_archive', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_column('include_archive')
    # ### end Alembic commands ###
