"""add admin table

Revision ID: fb0330cdce7a
Revises: a5eb1baf3410
Create Date: 2025-02-08 05:55:48.109535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0330cdce7a'
down_revision = 'a5eb1baf3410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_daily_cron', sa.DateTime(), server_default=sa.text("(datetime('2024-01-01 00:00:00'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
