"""Change plan_versioned_backups default to false

Revision ID: fe7706017c9b
Revises: 5b93bf0f9885
Create Date: 2025-07-25 04:35:37.313959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe7706017c9b'
down_revision = '5b93bf0f9885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_index('idx_file_account_id')
        batch_op.drop_index('idx_file_last_modified')

    with op.batch_alter_table('gateway', schema=None) as batch_op:
        batch_op.drop_index('idx_gateway_account_id')
        batch_op.drop_index('idx_gateway_created_at')
        batch_op.drop_index('idx_gateway_name')

    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.drop_index('idx_node_created_at')
        batch_op.drop_index('idx_node_gateway_id')
        batch_op.drop_index('idx_node_uuid')

    # Manually update plan_versioned_backups default value
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('plan_versioned_backups',
               existing_type=sa.Boolean(),
               server_default='false',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node', schema=None) as batch_op:
        batch_op.create_index('idx_node_uuid', ['uuid'], unique=False)
        batch_op.create_index('idx_node_gateway_id', ['gateway_id'], unique=False)
        batch_op.create_index('idx_node_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('gateway', schema=None) as batch_op:
        batch_op.create_index('idx_gateway_name', ['name'], unique=False)
        batch_op.create_index('idx_gateway_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_gateway_account_id', ['account_id'], unique=False)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.create_index('idx_file_last_modified', ['last_modified'], unique=False)
        batch_op.create_index('idx_file_account_id', ['account_id'], unique=False)

    # Manually revert plan_versioned_backups default value
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('plan_versioned_backups',
               existing_type=sa.Boolean(),
               server_default='true',
               existing_nullable=False)

    # ### end Alembic commands ###
